version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
    restart: always
 
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx-proxy
    restart: always

  gitbucket:
    image: shomatan/gitbucket
    ports:
      - 29418:29418
    environment:
      # nginx-proxy & letsencrypt
      VIRTUAL_HOST: ${GITBUCKET_DOMAIN}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ${GITBUCKET_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_TEST: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./gitbucket/repositories:/gitbucket/repositories
      - ./gitbucket/data:/gitbucket/data
      - ./gitbucket/plugins:/gitbucket/plugins
    restart: always

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: gitbucket
      POSTGRES_USER: gitbucket
      POSTGRES_PASSWORD: gitbucket
    volumes:
      - ./gitbucket/postgres:/var/lib/postgresql/data
    restart: always

  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      # registry
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/${DOCKER_REGISTRY_DOMAIN}/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/${DOCKER_REGISTRY_DOMAIN}/key.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./registry/registry:/var/lib/registry
      - ./certs/:/certs
      - ./registry/auth:/auth
    restart: always

  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    environment:
      ENV_DOCKER_REGISTRY_HOST: ${DOCKER_REGISTRY_DOMAIN}
      ENV_DOCKER_REGISTRY_PORT: 5000
      ENV_DOCKER_REGISTRY_USE_SSL: 1
      ENV_MODE_BROWSE_ONLY: ${MODE_BROWSE_ONLY} 
      # nginx-proxy & letsencrypt
      VIRTUAL_HOST: ${DOCKER_REGISTRY_DOMAIN}
      LETSENCRYPT_HOST: ${DOCKER_REGISTRY_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_TEST: "false"
    restart: always
